### ISSUE TITLE
Improvements to the linear algebra & testing

### ISSUE THREAD

**Issue by alcrene** [tadamcz/metalogistic#3]
Hi,

I made a few modifications on my fork, which you can see [here](https://github.com/alcrene/metalogistic/commits/master).
I also implemented some basic automatic differentiation, which was required by my use case. That's not nearly as clean, so it is in its [own branch](https://github.com/alcrene/metalogistic/commit/bd2828dde5a45249b70ccd87dc52b153a811e108).

Let me know if you would like any of that as a PR, and whether to make one PR or multiple.

Cheers,
Alexandre

**Comment by tadamcz** [comment]
Hi Alexandre, great to see this, thanks!

On the one hand, PRs would be great. On the other hand, I'm super busy and won't have time to prioritise reviewing and merging them soon (like probably not in the next 6 months). You can still make a PR and there's a good chance I'll eventually get to it (I do still care about this package and want to revisit it).

If you do so, please make multiple PRs. As modular as possible :)

**Comment by alcrene** [comment]
In that case I will hold off a bit in case anything else comes up, then package what I've got.
